[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=1
PauseHotkey=32
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=49dbce74-08b6-4572-adf2-0703031ab6fd
Description=[wow]自动按 -
Enable=1
AutoRun=0
[Repeat]
Type=1
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========

a = int(rnd() * 150) + 200
Delay a

KeyPress "-", 1



'==========以上是按键精灵录制的内容==========
